version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --save

      - run:
          name : Run all test
          command : |
            npm run test