version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: npm install --save

      - run:
          name : Run Single Test
          command : npm run single

      - run:
          name : Run Parallel Test
          command : npm run parallel