version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    working_directory: ~/code
    executor: win/default
    #docker:
    #  - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --save

      - run:
          name : Run all test
          command : |
            npm run test