version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --save

      - run:
          name : Run single test
          command : |
            npm run single
      
      -run:
        name: Run parallel test
        command: |
          npm run parallel